name: CD - Deploy to AWS

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd fastapi-book-project  # Update if necessary
            git reset --hard
            git pull origin main
            docker compose down || true  # Adjust for Docker Compose V2
            docker compose up -d --build
            docker ps
