name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  test:  # Important: job name must be exactly 'test' as per requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Matching our local version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: pytest
